# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.CharField(max_length=255)),
                ('Adress', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('group_name',),
            },
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('avartar', models.ImageField(upload_to='photos')),
                ('description', models.CharField(max_length=255)),
                ('EmailAdress', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
