# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mychama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chama',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['groupName']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='Adress',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.RemoveField(
            model_name='group',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='group',
            name='contribution_amnt',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='contribution_interval',
            field=models.CharField(blank=True, choices=[('d', 'Daily'), ('w', 'Weekly'), ('m', 'Monthly'), ('q', 'Quartely')], default='d', help_text='Contribution Intervals', max_length=1),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='groupName',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='paybillNo',
            field=models.PositiveIntegerField(default=122, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chama',
        ),
        migrations.AddField(
            model_name='membership',
            name='chama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychama.Group'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chama', through='mychama.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
