# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0002_auto_20190815_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contribution_interval',
            field=models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quartely')], default='d', help_text='Contribution Intervals', max_length=1),
        ),
    ]
