# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0002_auto_20190815_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Adress',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='individual',
            name='EmailAdress',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
