# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0003_auto_20190815_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='description',
        ),
    ]
