# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0004_remove_individual_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='natinal_id',
            field=models.CharField(default=36911503, max_length=150),
            preserve_default=False,
        ),
    ]
