# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0005_individual_natinal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='location',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
