# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0007_individual_contact_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='contact_adress',
            field=models.IntegerField(max_length=150),
        ),
    ]
