# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0011_auto_20190815_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=150)),
                ('natinal_id', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photos')),
                ('contact_adress', models.CharField(max_length=150)),
                ('EmailAdress', models.EmailField(blank=True, max_length=254)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychama.Group')),
            ],
            options={
                'ordering': ('member_name',),
            },
        ),
    ]
