# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0012_group_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_member',
            old_name='editor',
            new_name='group',
        ),
    ]
