# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychama', '0013_auto_20190815_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_contributed', models.CharField(max_length=150)),
                ('contribution_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychama.Group')),
            ],
            options={
                'ordering': ('group',),
            },
        ),
        migrations.CreateModel(
            name='Individual_contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_contributed', models.CharField(max_length=150)),
                ('contribution_date', models.DateTimeField(auto_now_add=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychama.Individual')),
            ],
            options={
                'ordering': ('individual',),
            },
        ),
    ]
